name: Python workflow

on: [push]

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Set up Python

       uses: actions/setup-python@v5
       with:
         python-version: '3.x'
         architecture: 'x64'
     - name: Display Python version
       run: python -c "import sys; print(sys.version)"
     - name: Install dependecies
       run: |
         python -m pip install --upgrade pip
     - name: Print the working directory
       run: |
         pwd
     - name: Execute python script # run file
       run: |
         python python/print_n_numbers.py
